# Generated by Django 5.1.2 on 2024-11-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('streaming', models.CharField(choices=[('AK', 'Amazon Kindle'), ('F', 'Fisico')], max_length=2)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField()),
                ('categories', models.ManyToManyField(to='books.categories')),
            ],
        ),
    ]
